// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xxsyrtfhghemgsbfdtpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqa3BseXBlc3h0cW14bnVxcmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5Nzk1NDEsImV4cCI6MjA2MzU1NTU0MX0._D2qBaRp9yoixid2XvsnD6biQTLjGit_hCkA7H_29EY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);